services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    container_name: ${CONTAINER_NAME_DB}
    ports:
      - "${DB_PORT}:3306"
    healthcheck: # 이 부분을 추가
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./data/mysql/mysql:/var/lib/mysql # 실제 MySql 데이터 파일들이 저장되는 볼륨
      - ./data/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf # MySQL 설정 파일 마운트
    environment:
      TZ: Asia/Seoul
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  nginx:
    container_name: ${CONTAINER_NAME_NGINX}
    image: nginx:latest
    ports:
      - ${NGNIX_PORT}:80

networks:
  saisai_nat: {}
