spring:
  application:
    name: saisai
  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 2MB

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_OPTION}
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100

  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      timeout: 6000ms
      port: ${REDIS_PORT}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 5000ms
      database: 0
      password: ${REDIS_PASSWORD}

server:
  error:
    include-message: ${ERROR_MESSAGE_TYPE}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

s3:
  bucket: ${S3_BUCKET_NAME}
  region: ${S3_REGION}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  endpoint: ${S3_ENDPOINT}
  base-path: ${S3_BASEPATH}

springdoc:
  swagger-ui:
    persist-authorization: true
    default-models-expand-depth: -1
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health


durunubi:
  secret: ${DURUNUBI_SECRET_KEY}

oauth2:
  google:
      android:
        client-id: ${GOOGLE_AND_CLIENT_ID}
      ios:
        client-id: ${GOOGLE_IOS_CLIENT_ID}
  apple:
    key: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    client-id: ${APPLE_CLIENT_ID}
    private-key: ${APPLE_PRIVATE_KEY}
  kakao:
    rest-key: ${KAKAO_REST_API_KEY}
    admin-key: ${KAKAO_ADMIN_KEY}

encrypt:
  key: ${ENCRYPT_KEY}
  iv: ${ENCRYPT_IV}
